db/member/CreateTable.sql

Gombo2-MEMBER -> main
close #4
close #8   
close #7 
close #9
close #10
MEMBER 도메인 관련 테이블 CRATET , DROP 문 작성
----

[Feat] member / 회원 도메인 관련 테이블 DDL

---

db/challenge/CreateChallengeTable.sql

feature/hm/challenge/createChallenge -> main
close #27
close #28 
close #29 
close #30 
close #31 
close #32 
close #33 
CHALLENGE 도메인 관련 테이블 CREATE, DROP문 작성
----

[Feat] challenge / 챌린지 도메인 관련 테이블 DDL

---

db/report/CreateReportTable.sql

feature/sh/report/refactoringReportTable -> main
close #60 
close #61
close #63 
- [Style] 컨벤션에 맞게 쉼표 앞으로 이동
- [Refactor] ENUM 타입 모두 TINYINT형으로 수정
----

[Refactor] report / 컨벤션에 맞게 코드 수정 및 변수 타입 수정

---

.github/ISSUE_TEMPLATE/issue_template_documentation.yaml
.github/ISSUE_TEMPLATE/issue_template_style.yaml

docs/sh/issueTemplate/updateTemplates -> main
close #이슈번호
- style 이슈 템플릿 수정
- docs 이슈 템플릿 생성

[Docs] git / 스타일 이슈 템플릿 수정 및 문서 템플릿 생성

---

db/matching/CreateMatchingTable.sql

feature/sw/matching/refactoringMatchingTable -> main
close #64 
close #65 
- 오타 수정: is_cancled -> is_canceled
- 변수명 수정: date 형태 -> date_at
- pk, fk 제약 조건 위치 수정
----

[Refactor] matching / 매칭 도메인 관련 테이블 DDL 구문 수정 

---

db/challenge/CreateChallengeTable.sql

feature/hm/challenge/createChallenge -> main
close #69 
CHALLENGE 도메인 관련 테이블 제약조건 수정
일일미션 테이블 날짜 삭제
회원별 일일미션 달성 날짜 컬럼명 수정 -> accepted_date
----
[ ] 제약조건 잘 들어갔는지

[Refactor] challenge / 챌린지 도메인 관련 테이블 제약조건 수정, 컬럼명 삭제 및 수정

---

db/post/CreateTablePost.sql

feature/cm/post/createTable
close #74 
close #75 
ENUM -> TINYINT로 수정
PK, FK, CONSTRAINT 이름 지정

[Refactor] post / ENUM -> TINYINT로 수정, PK, FK, CONSTRAINT 이름 지정

---

db/challenge/CreateChallengeTable.sql

feature/hm/challenge/updateChallenge -> main
close #77 
뱃지 테이블에 가산점 컬럼(advantage) 추가
----

[Refactor] challenge  / 뱃지 테이블에 가산점 컬럼 추가

---

db/challenge/SelectChallenge.sql

feature/hm/challenge/challengeSelect
close #88 
close #89 
close #90 
도전과제, 일일미션, 뱃지 관련 테이블에서 필요한 조회 기능 구현

[Feat] challenge/ 챌린지 도메인 관련 조회 기능 구현

---

db/member/CreateDummyData.sql
db/member/SelectAllMembers.sql
db/member/SelectEmailByNameAndPhone.sql
db/member/SelectExistsByEmail.sql
db/member/SelectExistsByPhoneNumber.sql
db/member/SelectExpAndLevelByMeberId.sql
db/member/SelectImagePathByMemberId.sql
db/member/SelectMemberById.sql
db/member/SelectMemberLanguageByMemberId.sql
db/member/SelectMemberProfliePageByMemberId.sql
db/member/SelectMemberStatus.sql
db/member/SelectPasswordByNamePhoneAndEmail.sql
db/member/SelectProgrammingLanguage.sql

- 이하 7가지
member-member
close #이슈번호
close #102 
----
빠진 조회기능이 있을까요

[Feat] member/ 회원 테이블 관련 select문 기능 구현

---

db/challenge/CreateChallengeTable.sql

refactor/hm/challenge/createChallenge
close #107 
일일미션 테이블 삭제여부 컬럼 오타 수정 s_deleted -> is_deleted
뱃지 테이블 가산점 컬럼 오타 수정 adventage -> advantage

[Refactor] challenge/ 챌린지 도메인 관련 테이블 DDL 수정

---

db/challenge/CreateChallengeTable.sql
db/challenge/InsertDummy.sql

refactor/hm/challenge/challengeSelect -> main
close #111 
뱃지 테이블 가산점 컬럼 오타 수정 adventage -> advantage

[Refactor] challenge/ 챌린지 도메인 관련 테이블 SELECT문, 더미데이터 수정

---

db/post/CreateTablePost.sql

feature/cm/post/createTablePostChangeComment
close #113 
status 컬럼에 활성화 여부 기본: 0, 삭제: 1, 규제: 2 주석 추가

[Comment] post / status 컬럼에 주석 추가

---

Pick/src/main/resources/com/nob/pick/achievement/query/mapper/AchievementQueryMapper.xml
Pick/src/main/resources/com/nob/pick/badge/query/mapper/BadgeQueryMapper.xml
Pick/src/main/resources/com/nob/pick/dailymission/query/mapper/DailyMissionQueryMapper.xml
Pick/src/main/resources/com/nob/pick/dailymission/query/mapper/MemberDailyMissionQueryMapper.xml

refactor/hm/challenge/refactorR -> main
close #112 
핸들러 위치 수정
com.nob.pick.config.typehandler.StringYnTypeHandler
-> com.nob.pick.**common**.config.typehandler.StringYnTypeHandler

[Refactor] challenge/ 챌린지 관련 도메인 handler 위치 수정

---

Pick/src/main/java/com/nob/pick/common/config/MybatisConfiguration.java
Pick/src/main/java/com/nob/pick/post/command/application/dto/CommentDTO.java
Pick/src/main/java/com/nob/pick/post/command/application/dto/MemberNicknameDTO.java
Pick/src/main/java/com/nob/pick/post/command/application/dto/PostCommentDTO.java
Pick/src/main/java/com/nob/pick/post/command/application/dto/PostDTO.java
Pick/src/main/java/com/nob/pick/post/command/application/dto/PostImageDTO.java
Pick/src/main/java/com/nob/pick/post/command/application/dto/PostListDTO.java
Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/entity/Post.java
Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/vo/ResponseCommentVO.java
Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/vo/ResponsePostCommentVO.java
Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/vo/ResponsePostImageVO.java
Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/vo/ResponsePostListVO.java
Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/vo/ResponsePostVO.java
Pick/src/main/java/com/nob/pick/post/query/controller/PostController.java
Pick/src/main/java/com/nob/pick/post/query/mapper/PostMapper.java
Pick/src/main/java/com/nob/pick/post/query/service/PostService.java
Pick/src/main/java/com/nob/pick/post/query/service/PostServiceImpl.java
Pick/src/main/resources/com/nob/pick/post/query/mapper/PostMapper.xml

feature/cm/post/mybatisPost1
close #164 
close #165 
close #166 
close #168 
- 전체 게시글 목록 조회 기능 구현
- 단일 게시글 세부 조회 기능 구현
- 게시글 제목 검색 기능 구현
> ENUM 타입 아직 적용 안 되어 있습니다.
> 일단 돌아가게만 짜두고 수정할 계획이니
> 고쳤으면 좋겠다 싶은 부분 코멘트로 써주세요
----
- 반복되는 코드 줄일 수 있는지

[Feat] post / 게시글 도메인 관련 조회 기능 구현

---

Pick/src/main/java/com/nob/pick/badge/query/controller/MemberBadgeQueryController.java

챌린지별 뱃지 조회 경로와 동일해서 변경
refactor/hm/badge/badgeSelect -> main
close #180 
챌린지별 뱃지와 경로가 동일하여 회원별 획득 뱃지 조회 경로 수정

[Refactor] badge / 회원별 획득 뱃지 경로 수정

---

Pick/src/main/java/com/nob/pick/common/config/typehandler/PostCategoryEnumTypeHandler.java
Pick/src/main/java/com/nob/pick/common/config/typehandler/PostStatusEnumTypeHandler.java
Pick/src/main/java/com/nob/pick/post/command/application/controller/CommandPostController.java
Pick/src/main/java/com/nob/pick/post/command/application/dto/CommentDTO.java
Pick/src/main/java/com/nob/pick/post/command/application/dto/PostCategory.java
Pick/src/main/java/com/nob/pick/post/command/application/dto/PostCommentDTO.java
Pick/src/main/java/com/nob/pick/post/command/application/dto/PostDTO.java
Pick/src/main/java/com/nob/pick/post/command/application/dto/PostListDTO.java
Pick/src/main/java/com/nob/pick/post/command/application/dto/PostStatus.java
Pick/src/main/java/com/nob/pick/post/command/application/service/CommandPostService.java
Pick/src/main/java/com/nob/pick/post/command/application/service/CommandPostServiceImpl.java
Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/entity/Post.java
Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/vo/ResponseCommentVO.java
Pick/src/main/java/com/nob/pick/post/command/domain/aggregate/vo/ResponseRegisterPostVO.java
Pick/src/main/java/com/nob/pick/post/command/domain/repository/PostRepository.java
Pick/src/main/java/com/nob/pick/post/query/controller/PostController.java
Pick/src/main/java/com/nob/pick/post/query/mapper/PostMapper.java
Pick/src/main/java/com/nob/pick/post/query/service/PostService.java
Pick/src/main/java/com/nob/pick/post/query/service/PostServiceImpl.java
Pick/src/main/resources/com/nob/pick/post/query/mapper/PostMapper.xml

feature/cm/post/jpa1 -> main
close #186 
close #188 
close #190 
close #192 
- 게시글 등록 기능 추가
- 게시글 삭제 기능 추가
- 단일 게시글 기능 수정
- 게시글 카테고리, 상태 ENUM으로 관리하도록 TypeHandler 추가 및 Mapper 수정
----
- 단일 게시글 조회 시 댓글이나 사진이 하나도 없으면 조회되지 않는 현상 수정

[Feat] post / 게시글 등록, 삭제 기능 구현 + [Fix] post / 단일 게시글 조회 수정

---

Pick/src/main/java/com/nob/pick/report/query/controller/ReportController.java
Pick/src/main/java/com/nob/pick/report/query/dao/ReportMapper.java
Pick/src/main/java/com/nob/pick/report/query/service/ReportService.java
Pick/src/main/java/com/nob/pick/report/query/service/ReportServiceImpl.java
Pick/src/main/resources/com/nob/pick/report/query/dao/ReportMapper.xml

Feature/sh/report/select report2 -> main
close #126 
close #169 
- 상태별 신고 목록 조회 (처리중, 보류, 승인)
- 삭제 여부별 신고 목록 조회
----
- 추가해야할 조회 목록이 있는지

[Feat] report / Report 도메인 관련 조회 기능 추가 구현

---

Pick/src/main/java/com/nob/pick/regulation/query/controller/RegulationController.java
Pick/src/main/java/com/nob/pick/regulation/query/dao/RegulationMapper.java
Pick/src/main/java/com/nob/pick/regulation/query/dto/RegulationDTO.java
Pick/src/main/java/com/nob/pick/regulation/query/service/RegulationService.java
Pick/src/main/java/com/nob/pick/regulation/query/service/RegulationServiceImpl.java
Pick/src/main/resources/com/nob/pick/regulation/query/dao/RegulationMapper.xml

Feature/sh/regulation/select regulation -> main
close #127 
close #128 
close #130 
close #194 
- 전체 규제 목록 조회
- 특정 회원 규제 목록 조회
- 규제 테이블 삭제 여부 추가
- 삭제 여부별 규제 목록 조회
----

[Feat] regulation / Regulation 도메인 관련 조회 구현

---

Pick/src/main/java/com/nob/pick/regulation/command/application/controller/RegulationController.java
Pick/src/main/java/com/nob/pick/regulation/command/application/dto/RegulationDTO.java
Pick/src/main/java/com/nob/pick/regulation/command/application/service/RegulationImpl.java
Pick/src/main/java/com/nob/pick/regulation/command/application/service/RegulationService.java
Pick/src/main/java/com/nob/pick/regulation/command/domain/aggregate/Regulation.java
Pick/src/main/java/com/nob/pick/regulation/command/domain/repository/RegulationRepository.java

Feature/sh/regulation/regulationJPA -> main
close #196 
close #197 
- JPA를 활용해 Regulation 데이터 등록 구현
- Regulation 데이터 soft delete 구현
----

[Feat] regulation / Regulation 등록, 삭제 기능 구현

---

Pick/src/main/java/com/nob/pick/post/command/application/controller/CommandPostController.java

feature/cm/post/jpa2 -> main
close #217 
- Front-end에서 사용되는 GetMapping 삭제
- deletePost 리턴 타입 ResponseEntity로 변경
- 반복 사용되는 메소드 DTO로 최소한만 받아오게 변경

[Refactor] post / CommandPostController 일부 수정

---

kick-member/src/main/resources/com/nob/kickmember/member/query/mapper/MemberMapper.xml

refactor : xml파일 누락 수정

---

README.md

[Readme] 프로젝트 관련 API TEST 캡쳐본

---

BE14-NoB/config/masconfig.yml

Refactor/sh/config/masconfig
close #이슈번호
- 잘못 올라간 config 파일 삭제

[Refactor] server / 잘못 올라간 msaconfig.yml 파일 삭제

---

Pick/src/main/java/com/nob/pick/post/command/application/controller/CommandPostController.java
Pick/src/main/java/com/nob/pick/post/command/application/service/CommandPostService.java
Pick/src/main/java/com/nob/pick/post/command/application/service/CommandPostServiceImpl.java
Pick/src/test/java/com/nob/pick/post/DeletePostTest.java

feature/cm/post/test1 -> main
close #230 
close #241 
Post 삭제 테스트 코드 추가

[Test] post / 삭제 테스트 코드 추가

---

.gitignore
Pick/src/test/java/com/nob/pick/report/query/service/ReportServiceImplTest.java

feature/sh/report/testcode -> main
close #246 
- 신고 테이블 조회 관련 테스트 코드 작성
----

[test] report / 테스트 코드 작성

---

Pick/src/main/java/com/nob/pick/regulation/command/application/controller/RegulationController.java
Pick/src/main/java/com/nob/pick/regulation/command/application/service/RegulationImpl.java
Pick/src/main/java/com/nob/pick/regulation/command/application/service/RegulationService.java
Pick/src/main/java/com/nob/pick/report/command/application/controller/ReportController.java

chore/sh/report/logging -> main
close #253 
close #254
- 신고 등록 결과 메세지 추가
- 규제 등록 결과 메세지 추가

[Chore] report, regulation / insert 관련 결과 메세지 추가

---

BE14-NoB/config/masconfig.yml
BE14-NoB/config/msaconfig.yml
kick-member/src/main/java/com/nob/kickmember/member/query/dto/MemberProfilePageDTO.java
kick-member/src/main/resources/com/nob/kickmember/member/query/mapper/MemberMapper.xml
kick-member/src/test/java/com/nob/kickmember/member/query/service/MemberServiceTest.java

MemberTestCase -> main
close #이슈번호
close #258 
----

[Test] 회원 조회 관련 service 계층 테스트케이스 작성

---

Pick/src/main/resources/com/nob/pick/matching/query/mapper/MatchingMapper.xml

fix/sw/handler
close #이슈번호
타입 핸들러 mapper.xml내에 매핑 정보 입력
----

[Hotfix] matching mapper.xml에 핸들러 매핑

---

README.md

docs/sh/readme2 -> main
리드미 반영을 위한 업데이트

[Docs] 리드미 업데이트

---

Pick/src/main/java/com/nob/pick/infrastructure/FeignClientConfig.java
Pick/src/main/java/com/nob/pick/infrastructure/MemberServiceClient.java
Pick/src/main/java/com/nob/pick/matching/query/service/MatchingServiceImpl.java
Pick/src/main/java/com/nob/pick/matching/query/vo/ResponseMemberProfileVO.java

featue/sw/member/matching
close #279
- feign 클라이언트를 이용해 kick-member에 접근
----

Feat: kick-member의 프로필 정보 가져오기 구현

---

Pick/src/main/java/com/nob/pick/regulation/command/application/service/RegulationServiceImpl.java
Pick/src/main/java/com/nob/pick/regulation/query/dto/RegulationDTO.java
Pick/src/main/java/com/nob/pick/report/query/controller/ReportController.java
Pick/src/main/java/com/nob/pick/report/query/dto/ReportDTO.java
Pick/src/main/resources/com/nob/pick/regulation/query/dao/RegulationMapper.xml
Pick/src/main/resources/com/nob/pick/report/query/dao/ReportMapper.xml

Refactor/sh/refactoring task -> main
close #278 
close #281 
close #282 
close #284 
- Date타입인 변수들 LocalDate 타입으로 수정
- 핸들러 전역 처리로 인한 코드 삭제
- User로 되어있던 메서드 이름 수정
- RegulationImple 클래스 RegulationServiceImpl로 수정

[Refactor] report, regulation / 코드 리팩토링

---

db/member/CreateDummyData.sql
db/member/CreateMemberTable.sql
db/member/SelectAllMembers.sql
db/member/SelectMemberById.sql

refactor/sy/member/reported -> main
close #이슈번호
close #307 
- reported_count -> regulated_count 필드명 변경
----
- DB 더미데이터 삽입, 테이블 생성 부분에서 안바뀐 부분있는지

[member] refactor : 멤버 테이블 필드명 변경

---

README.md
kick-member/src/main/java/com/nob/kickmember/member/command/entity/Member.java
kick-member/src/main/java/com/nob/kickmember/member/query/dto/MemberDTO.java
kick-member/src/main/resources/com/nob/kickmember/member/query/mapper/MemberMapper.xml
kick-member/src/test/java/com/nob/kickmember/member/query/service/MemberServiceTest.java

refactor/sy/member/regulated
close #이슈번호
close #307 
reported_count -> regulated_count
- 변경 사항 1: 멤버 엔티티 변경
- 변경 사항 2: 멤버 DTO 변경
- 변경 사항 3: 매퍼xml resultmap 변경
- 변경 사항 4: 서비스단 테스트케이스 더미데이터 변경
----
- 위에 해당사항 말고 제 도메인에서 신고 처리 횟수 관련 변경해야 하는거 빠진거 있는지

[Refactor] member / 멤버 도메인 관련 필드명 변경

---

Pick/src/main/java/com/nob/pick/common/util/JwtFilter.java
Pick/src/main/java/com/nob/pick/common/util/JwtUtil.java
Pick/src/main/java/com/nob/pick/common/util/WebSecurity.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/controller/GitHubAccountController.java
Pick/src/main/java/com/nob/pick/gitactivity/command/domain/aggregate/GitHubAccount.java
Pick/src/main/java/com/nob/pick/gitactivity/query/service/GitHubAccountServiceImpl.java

refactor/sh/refactorGitAPI -> main
close #330
- 깃 관련 파일 들여쓰기 수정

[Style] gitapi 관련 파일들 들여쓰기 수정

---

Pick/src/main/java/com/nob/pick/gitactivity/command/application/controller/GitHubAccountController.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/controller/GitHubActivityController.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/dto/CommitDTO.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/dto/IssueDTO.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/dto/LabelDTO.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/dto/PullRequestDTO.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/service/GitHubAccountService.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/service/GitHubAccountServiceImpl.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/service/GitHubActivityService.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/service/GitHubActivityServiceImpl.java
Pick/src/main/java/com/nob/pick/gitactivity/command/domain/aggregate/GitHubAccount.java
Pick/src/main/java/com/nob/pick/gitactivity/command/domain/repository/GitHubAccountRepository.java

Feature/sh/git-ud -> main
close #347
close #348 
close #349 
- 깃 이슈 목록 조회 기능 구현
- 깃 커밋 목록 조회 기능 구현
- 깃 PR 목록 조회 기능 구현
----

[Feature] 깃 커밋, 이슈, PR 조회 기능 구현

---

Pick/src/main/java/com/nob/pick/common/util/JwtUtil.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/controller/GitHubAccountController.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/controller/GitHubActivityController.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/dto/BranchDiffDTO.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/dto/ChangedFileDTO.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/dto/IssueDTO.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/service/GitHubActivityService.java
Pick/src/main/java/com/nob/pick/gitactivity/command/application/service/GitHubActivityServiceImpl.java

Feature/sh/git/link front -> main
close #355 
close #354
- 이슈 생성 API용 gateway 서버 업로드
- 프론트 연결을 위해 jwt 토큰 주석 처리
- 이슈 상태(open/closed) 확인 가능하게 DTO 수정
- 깃 브랜치 목록 연동
- 브랜치별 커밋 목록 조회
- PR 생성 기능 구현

[Feature] git / 깃 API 프론트 연동

---

Pick/src/main/java/com/nob/pick/gitactivity/command/application/service/GitHubActivityServiceImpl.java

refactor/sh/git/branch -> main
close #359
- 모든 브랜치를 조회하는 기능에서 안닫힌 PR과 관련된 브랜치만 조회하는 기능으로 수정
----

[Refactor] git / 닫히지 않은 PR과 관련된 브랜치만 조회
